"""add pipeline_warnings to agent_thesis

Revision ID: 59ed11edc7f3
Revises: b13c088bade6
Create Date: 2026-07-03 19:49:35.986994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ed11edc7f3'
down_revision: Union[str, Sequence[str], None] = 'b13c088bade6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_warnings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_thesis', schema=None) as batch_op:
        batch_op.drop_column('pipeline_warnings')

    # ### end Alembic commands ###
