"""initial schema

Revision ID: b13c088bade6
Revises: 
Create Date: 2026-07-03 13:09:51.712746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13c088bade6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_symbol'), ['symbol'], unique=False)

    op.create_table('agent_thesis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('quant_narrative', sa.String(), nullable=False),
    sa.Column('quant_key_factors', sa.JSON(), nullable=False),
    sa.Column('quant_score_breakdown', sa.JSON(), nullable=False),
    sa.Column('quant_overall_score', sa.Float(), nullable=False),
    sa.Column('financial_company_health', sa.String(), nullable=True),
    sa.Column('financial_growth', sa.String(), nullable=True),
    sa.Column('financial_profitability', sa.String(), nullable=True),
    sa.Column('financial_cash_flow', sa.String(), nullable=True),
    sa.Column('financial_analyst_consensus', sa.String(), nullable=True),
    sa.Column('financial_narrative', sa.String(), nullable=True),
    sa.Column('news_sentiment', sa.String(), nullable=True),
    sa.Column('news_summary', sa.String(), nullable=True),
    sa.Column('news_catalysts', sa.JSON(), nullable=True),
    sa.Column('news_risks', sa.JSON(), nullable=True),
    sa.Column('macro_regime', sa.String(), nullable=True),
    sa.Column('macro_outlook', sa.String(), nullable=True),
    sa.Column('macro_summary', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_concerns', sa.JSON(), nullable=True),
    sa.Column('risk_position_sizing_note', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('strategy_rationale', sa.String(), nullable=True),
    sa.Column('thesis', sa.String(), nullable=False),
    sa.Column('consensus', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('indicator_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=False),
    sa.Column('sma_50', sa.Float(), nullable=False),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=False),
    sa.Column('ema_26', sa.Float(), nullable=False),
    sa.Column('adx_14', sa.Float(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=False),
    sa.Column('macd', sa.Float(), nullable=False),
    sa.Column('macd_signal', sa.Float(), nullable=False),
    sa.Column('macd_histogram', sa.Float(), nullable=False),
    sa.Column('stoch_k', sa.Float(), nullable=False),
    sa.Column('stoch_d', sa.Float(), nullable=False),
    sa.Column('bb_upper', sa.Float(), nullable=False),
    sa.Column('bb_middle', sa.Float(), nullable=False),
    sa.Column('bb_lower', sa.Float(), nullable=False),
    sa.Column('atr_14', sa.Float(), nullable=False),
    sa.Column('obv', sa.Float(), nullable=False),
    sa.Column('volume_sma_20', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scored_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('max_loss', sa.Float(), nullable=False),
    sa.Column('max_gain', sa.Float(), nullable=True),
    sa.Column('breakeven', sa.Float(), nullable=False),
    sa.Column('reward_risk_ratio', sa.Float(), nullable=True),
    sa.Column('probability_of_profit', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_resistance_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('level_type', sa.String(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('last_touch_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('adx', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('volume_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('relative_volume', sa.Float(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_assessment')
    op.drop_table('trend_assessment')
    op.drop_table('support_resistance_level')
    op.drop_table('scored_candidate')
    op.drop_table('recommendation')
    op.drop_table('indicator_snapshot')
    op.drop_table('agent_thesis')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_symbol'))

    op.drop_table('analysis_run')
    # ### end Alembic commands ###
